# Generated by Django 3.1 on 2020-08-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='mean',
            field=models.TextField(),
        ),
    ]
